feat: Start MeteredDataForMeasurementPoint orchestration from EDI
Energinet-DataHub/opengeh-edi pull request #1425
Opened 2024-12-18 07:50 UTC by AndersBallingPetersen

## Description
Before:
MeteredDataForMeasurementPoint created the RSM-012 message directly in EDI without interaction with the ProcessManager.

Now:
MeteredDataForMeasurementPoint starts a new orchestration using the ProcessManagerClient.

FYI: The Featureflag for MeteredDataForMeasurementPoint is checked in Energinet.DataHub.EDI.B2BApi.IncomingMessages.IncomingMessageReceiver

## References

## Checklist
- [ ] Should the change be behind a feature flag?
- [ ] Can the feature be meaningfully disabled or circumvented if there are issues (e.g., database-breaking changes)?
- [ ] Has it been considered whether data is being delivered to the wrong actor?
- [ ] Subsystem test executed (dev_002/dev_003)
- [ ] Is there time to monitor state of the release to Production?
- [ ] Reference to the task

2024-12-18 07:57 UTC, MWO1024 commented on source/IncomingMessages.Infrastructure/ProcessManager/IRequestProcessOrchestrationStarter.cs
> +        InitializeMeteredDataForMeasurementPointMessageProcessDto initializeProcessDto,
In the PM the orch is know as `Orchestration_Brs_021_ForwardMeteredData_V1`. We should consider aligning them a bit more I think.
Maybe use `StartForwardMeteredDataForMeasurementPointOrchestrationAsync` here?

2024-12-18 07:59 UTC, MWO1024 commented on source/Process.Application/ProcessInitializationHandlers/InitializeAggregatedMeasureDataHandler.cs
>  using MediatR;
Changes in this file seem redundant.

2024-12-18 08:27 UTC, MWO1024 requested changes
I think we should deploy this to d002 before a merge, to see the subsystemtests and systemtests are happy. Additionally, we can try to throw an RSM-12 at the deployed system and validate that it does not break.

2025-01-06 11:47 UTC, MadsDue commented on source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
> +        var expectedQuantityQuality = "1001";
```suggestion
        var expectedEnergyQuantity = "1001";
        var expectedQuantityQuality = "A03";
```

2025-01-06 11:47 UTC, MadsDue commented on source/Tests/Infrastructure/IncomingMessages/RequestProcessOrchestrationStarterTests.cs
> +            ActorNumber.Create("1234567890123"),
Should this not match the requestedByActor?

2025-01-06 11:47 UTC, MadsDue commented on source/IncomingMessages.Infrastructure/ProcessManager/RequestProcessOrchestrationStarter.cs
> +                        RegistrationDateTime: InstantPattern.General.Parse(initializeProcessDto.CreatedAt).Value.ToString(),
This should be the RegisteredAt date instead of CreatedAt. 

I can see that InitializeMeteredDataForMeasurementPointMessageSeries is missing the RegisteredAt field as well.
![image](https://github.com/user-attachments/assets/1ecf7189-3282-4607-8424-e014bfc112b1)

Map the value from the field here: InitializeMeteredDataForMeasurementPointProcessDtoFactory.cs
![image](https://github.com/user-attachments/assets/51bdf435-6bd4-4a0a-aa89-b8616f389b1a)

2025-01-06 12:12 UTC, MadsDue approved these changes
LGTM

2025-01-14 14:47 UTC, MadsDue approved these changes

2025-01-15 06:05 UTC, MWO1024 approved these changes

2025-01-15 06:44 UTC, merged