fix: broken EF commit for message id and transaction id
Energinet-DataHub/opengeh-edi pull request #679
Opened 2023-12-13 10:11 UTC by MadsDue

## Description
We are not storing TransactionId or MessageId to ensure it can't be reused!
## References

2023-12-15 09:51 UTC, ebbeknudsen requested changes

2023-12-15 09:51 UTC, ebbeknudsen commented on source/BuildingBlocks.Infrastructure/IUnitOfWork.cs
> +using Microsoft.EntityFrameworkCore.Storage;
Er dette en fejl?

2023-12-15 09:51 UTC, ebbeknudsen commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +        catch (NotSuccessfulTransactionIdsStorageException)
Dette sker vel først når der kaldes `SaveChangesAsync()`, så det er den vi skal have en try/catch rundt om

2023-12-15 09:51 UTC, ebbeknudsen commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +    public async Task<ResponseMessage> HandleAsync(
Jeg syntes vi skal navngive den efter hvad den gør i stedet for `HandleAsync()`. Måske noget ala' `ReceiveMessageAsync()`, `RegisterMessageAsync()` eller `RegisterAndSendAsync()`

2023-12-15 09:51 UTC, ebbeknudsen commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +        using var transaction = await _incomingMessagesContext.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
Vi behøver ikke at starte vores transaction før der hvor vi kalder SaveChangesAsync(), ellers låser vi bare potentielt vores tabel unødigt

2023-12-15 09:51 UTC, ebbeknudsen commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +        catch (NotSuccessfulTransactionIdsStorageException)
Måske vi mangler test på at vi fanger `DuplicateTransactionIdDetected` eller `DuplicateMessageIdDetected`? For som det er nu så kan jeg ikke se at vi får en specific fejl tilbage hvis der er duplicates, udover at `SaveChangesAsync()` vil kaste en `DbUpdateException` eller lignende

2023-12-17 07:07 UTC, lasrinnil commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +    private async Task<Result> SaveMessageIdAndTransactionIdAsync(
Could we discuss this in person on monday? :)

2023-12-18 06:27 UTC, lasrinnil commented on source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
> +        Assert.Multiple(
Wow - this 11-line assert is massive! Perhaps a comment would help those not enlightened :)

2023-12-18 07:36 UTC, MadsDue commented on source/IncomingMessages.Application/IncomingMessageClient.cs
> +    private async Task<Result> SaveMessageIdAndTransactionIdAsync(
Of caurse :D

2023-12-18 07:38 UTC, MadsDue commented on source/IntegrationTests/Application/IncomingMessages/WhenIncomingMessagesIsReceivedTests.cs
> +        Assert.Multiple(
Good catch, I will make it more readable and aligned with this case

2023-12-18 10:20 UTC, ebbeknudsen approved these changes

2023-12-19 08:20 UTC, merged