feat: remove authentication method for test purpose
Energinet-DataHub/opengeh-edi pull request #717
Opened 2024-01-08 13:04 UTC by MadsDue

## Description

## References

2024-01-09 09:05 UTC, ebbeknudsen commented on source/AcceptanceTests/AcceptanceTestFixture.cs
> -        _azureEntraBackendBffScope = root.GetValue<string>("AZURE_ENTRA_BACKEND_BFF_SCOPE") ?? "https://devDataHubB2C.onmicrosoft.com/backend-bff/api";
Bliver disse ikke stadig brugt? Jeg tror bare de er udkommenterede, men de bliver brugt i b2c testene som Andreas sidder med :)

2024-01-09 09:10 UTC, ebbeknudsen commented on source/AcceptanceTests/Drivers/EdiDriver.cs
> -        var token = overrideToken ?? TokenBuilder.BuildToken(actorNumber, marketRoles, _azpToken);
You might consider looking at `CreateB2CAuthorizedHttpClientAsync` in `AcceptanceTestFixture`, it is set up so it only retreives the token once, to save time if it's used by multiple tests

2024-01-12 10:26 UTC, andpou commented on source/AcceptanceTests/Drivers/Ebix/EbixDriver.cs
> +            return; // temp fix for no content when peeking
Skulle vi tage og throw den givne exception her så vi får loggingen med?

2024-01-12 10:56 UTC, andpou commented on source/AcceptanceTests/Drivers/EdiActorDriver.cs
> +        Assert.NotNull(exist);
Giver det mening at have en assertion når det ikke er en test? Skal det måske være et regulært null tjek hvor vi smider en exception hvis den er null?

2024-01-12 11:07 UTC, andpou commented on source/AcceptanceTests/Tests/B2BErrors/WhenPayloadDataIsDifferentFromTokenDataTests.cs
> -        Output.WriteLine(response);
Tror der er røget en linje for meget i maskinen her 👍

2024-01-12 11:13 UTC, andpou requested changes

2024-01-12 11:13 UTC, andpou commented on source/AcceptanceTests/Drivers/Ebix/EbixDriver.cs
> +            return; // temp fix for no content when peeking
Skulle vi tage og throw den givne exception her så vi får loggingen med?

2024-01-12 11:13 UTC, andpou commented on source/AcceptanceTests/Drivers/EdiActorDriver.cs
> +        Assert.NotNull(exist);
Giver det mening at have en assertion når det ikke er en test? Skal det måske være et regulært null tjek hvor vi smider en exception hvis den er null?

2024-01-12 11:13 UTC, andpou commented on source/AcceptanceTests/Tests/B2BErrors/WhenPayloadDataIsDifferentFromTokenDataTests.cs
> -        Output.WriteLine(response);
Tror der er røget en linje for meget i maskinen her 👍

2024-01-12 11:31 UTC, MadsDue commented on source/AcceptanceTests/Drivers/Ebix/EbixDriver.cs
> +            return; // temp fix for no content when peeking
This is just a workaround to make the acceptance run green. 
It will be removed in another pr as part of my current task :)

2024-01-12 11:33 UTC, MadsDue commented on source/AcceptanceTests/Tests/B2BErrors/WhenPayloadDataIsDifferentFromTokenDataTests.cs
> -        Output.WriteLine(response);
good catch

2024-01-15 06:28 UTC, lasrinnil commented on source/AcceptanceTests/Drivers/EdiDriver.cs
> +using Nito.AsyncEx;
Is this dependency required for this to work?

2024-01-15 06:31 UTC, lasrinnil approved these changes

2024-01-15 07:06 UTC, MadsDue commented on source/AcceptanceTests/Drivers/EdiDriver.cs
> +using Nito.AsyncEx;
Yes :D it's giving us AsyncLazy

2024-01-15 07:30 UTC, andpou approved these changes

2024-01-15 07:30 UTC, merged