chore: remove unnecessary aggregation model
Energinet-DataHub/opengeh-edi pull request #780
Opened 2024-02-09 07:44 UTC by MadsDue

## Description

## References

2024-02-09 14:03 UTC, lasrinnil approved these changes

2024-02-09 19:10 UTC, RasmusGraabaek requested changes

2024-02-09 19:10 UTC, RasmusGraabaek commented on source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> +        var gridAreaDetails = await GetGridAreaDetailsAsync(aggregatedTimeSerie.GridAreaDetails.GridAreaCode, cancellationToken).ConfigureAwait(false);
Can we skip this step and use the gridAreaCode from aggregatedTImeSeries at line 60 instead?

2024-02-09 19:10 UTC, RasmusGraabaek commented on source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> +        var gridAreaDetails = await GetGridAreaDetailsAsync(integrationEvent, cancellationToken).ConfigureAwait(false);
nit: Should we have a condition on this fetch, since line 85 indicates that we may fetch gridAreaDetails and not make use of it. 
I.e. if the message is to a energy supplier or balance responsible?

Or am I missing something?

2024-02-12 07:44 UTC, MadsDue commented on source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> +        var gridAreaDetails = await GetGridAreaDetailsAsync(integrationEvent, cancellationToken).ConfigureAwait(false);
It is also use on line 88

2024-02-12 07:48 UTC, MadsDue commented on source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> +        var gridAreaDetails = await GetGridAreaDetailsAsync(aggregatedTimeSerie.GridAreaDetails.GridAreaCode, cancellationToken).ConfigureAwait(false);
I think it is good for now. 

We need to do something with this GridAreaDetails in generel and now I just kept it similary to the mapping from EnergyResultProducedV2. 

I will bring it up in our dev meet up today :D

2024-02-12 07:58 UTC, RasmusGraabaek approved these changes

2024-02-12 08:01 UTC, merged