feat: Initial steps to establish connection between archived messages
Energinet-DataHub/opengeh-edi pull request #787
Opened 2024-02-17 19:49 UTC by RasmusGraabaek

## Description
We need to establish a connection between a request from an actor and the corresponding request.
Hence this pull request add a new field to store the id of the request.

## References

2024-02-17 20:02 UTC, RasmusGraabaek commented on source/OutgoingMessages.Domain/OutgoingMessages/Queueing/Bundle.cs
> +    // If this attribute is set, then the messages in the bundle are responses to a request from an actor
summary

2024-02-17 20:03 UTC, RasmusGraabaek commented on source/OutgoingMessages.Domain/OutgoingMessages/Queueing/OutgoingMessage.cs
> +        public MessageId? RelatedToMessageId { get; set; }
Summary

2024-02-17 20:04 UTC, RasmusGraabaek commented on source/OutgoingMessages.Interfaces/Models/OutgoingMessageDto.cs
> +    public MessageId? RelatedToMessageId { get; }
summary

2024-02-17 20:04 UTC, RasmusGraabaek commented on source/OutgoingMessages.Interfaces/Models/OutgoingMessageId.cs
> +// TODO: Is this just a messageId now?
!

2024-02-19 11:12 UTC, ebbeknudsen requested changes

2024-02-19 11:12 UTC, ebbeknudsen commented on source/OutgoingMessages.Infrastructure/OutgoingMessages/Queueing/ActorMessageQueueEntityConfiguration.cs
> +            navigationBuilder.Property<MessageId>("RelatedToMessageId").HasColumnName("RelatedToMessageId")
Can't we just use lambda's? Don't we only need to usedstrings if the properties are private:
`navigationBuilder.Property(p => p.RelatedToMessageId)`

This also exposes an error in the conversion, since `toDbValue` is nullable but we just use `toDbValue.Value` without checking first. So:
```c#
navigationBuilder.Property(p => p.RelatedToMessageId)
                .HasConversion(
                    toDbValue => toDbValue != null ? toDbValue.Value : null,
                    fromDbValue => fromDbValue != null ? MessageId.Create(fromDbValue) : null);
```

2024-02-19 11:12 UTC, ebbeknudsen commented on source/OutgoingMessages.Interfaces/Models/OutgoingMessageId.cs
> +// TODO: Is this just a messageId now?
No :)

2024-02-19 11:12 UTC, ebbeknudsen commented on source/Process.Application/Transactions/AggregatedMeasureData/InitializeAggregatedMeasureDataProcessesHandler.cs
> +                    MessageId.Create(dto.MessageId),
Should probably move this outside the foreach like the `businessReason` to symbolize that it isn't coupled to the serie, but to the dto itself (and for a mini performance gain)

2024-02-19 11:12 UTC, ebbeknudsen commented on source/Process.Application/Transactions/Aggregations/AggregationMessageResultFactory.cs
> +            relatedToMessageWithMessageId: aggregatedMeasureDataProcess.InitiatedByMessageId);
```suggestion
            relatedToMessageId: aggregatedMeasureDataProcess.InitiatedByMessageId);
```

2024-02-19 12:09 UTC, ebbeknudsen submitted a review, later dismissed

2024-02-19 12:14 UTC, ebbeknudsen approved these changes

2024-02-19 12:14 UTC, ebbeknudsen approved these changes

2024-02-19 12:20 UTC, merged