refac: Move DocumentWriters
Energinet-DataHub/opengeh-edi pull request #966
Opened 2024-04-15 18:51 UTC by lasrinnil

## Description
All of the `DocumentWriter` implementations were placed into a `MarketDocuments` namespace. So I moved the writes into the `DocumentWriters` namespace.

Went from this:

To this:
![image](https://github.com/Energinet-DataHub/opengeh-edi/assets/6780460/137a0019-68bf-4da5-9c75-2c49bf4b7bd6)

## References

2024-04-16 13:26 UTC, ebbeknudsen requested changes

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Application/Usecases/Peek.cs
> +public class Peek
Maybe `PeekMessage` or `PeekOutgoingMessage`?

2024-04-16 13:26 UTC, ebbeknudsen commented on source/ArchitectureTests/RegistrationTests.cs
> +            return typeof(NotifyAggregatedMeasureDataXmlXmlDocumentWriter).Assembly.GetTypes()
Is the double `Xml` in name intentional?

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Xml/XmlDocumentWriter.cs
> +public abstract class XmlDocumentWriter : IDocumentWriter
```suggestion
public abstract class CimXmlDocumentWriter : IDocumentWriter
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/Formats/CIM/Xml/XmlHeaderWriter.cs
>  internal static class XmlHeaderWriter
```suggestion
internal static class CimXmlHeaderWriter
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataXmlXmlDocumentWriter.cs
> +public class NotifyAggregatedMeasureDataXmlXmlDocumentWriter : XmlDocumentWriter
```suggestion
public class NotifyAggregatedMeasureDataXmlDocumentWriter : XmlDocumentWriter
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyWholesaleServices/NotifyWholesaleServicesXmlXmlDocumentWriter.cs
> +    public NotifyWholesaleServicesXmlXmlDocumentWriter(IMessageRecordParser parser)
```suggestion
    public NotifyWholesaleServicesXmlDocumentWriter(IMessageRecordParser parser)
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/RejectRequestAggregatedMeasureData/RejectRequestAggregatedMeasureDataXmlXmlDocumentWriter.cs
> +public class RejectRequestAggregatedMeasureDataXmlXmlDocumentWriter : XmlDocumentWriter
```suggestion
public class RejectRequestAggregatedMeasureDataXmlDocumentWriter : XmlDocumentWriter
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/DocumentWriters/RejectRequestWholesaleSettlement/RejectRequestWholesaleSettlementXmlXmlDocumentWriter.cs
> +public class RejectRequestWholesaleSettlementXmlXmlDocumentWriter : XmlDocumentWriter
```suggestion
public class RejectRequestWholesaleSettlementXmlDocumentWriter : XmlDocumentWriter
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/Queueing/Bundels/Bundle.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.Bundels;
```suggestion
namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.Bundles;
```

2024-04-16 13:26 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/Queueing/Bundels/BundleId.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.Bundels;
```suggestion
namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.Bundles;
```

2024-04-16 13:32 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/Queueing/OutgoingMessages/IOutgoingMessageRepository.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.OutgoingMessages
Does the `Queueing` folder make sense? Maybe we should just move the `Bundels` (`Bundles`) and the `OutgoingMessages` into the root folder

2024-04-17 06:37 UTC, lasrinnil commented on source/ArchitectureTests/RegistrationTests.cs
> +            return typeof(NotifyAggregatedMeasureDataXmlXmlDocumentWriter).Assembly.GetTypes()
This is Rsharper, good catch ill fit it. Only one XML is needed :)

2024-04-17 06:38 UTC, lasrinnil commented on source/OutgoingMessages.Application/Usecases/Delegation.cs
> +public class Delegation
Lets go with the <usecase>message approch 👍

2024-04-17 07:25 UTC, lasrinnil commented on source/OutgoingMessages.Domain/Queueing/OutgoingMessages/IOutgoingMessageRepository.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.OutgoingMessages
how about this change:
![image](https://github.com/Energinet-DataHub/opengeh-edi/assets/6780460/5e6f046e-5f63-46ba-97a6-56b3aed72a39)

2024-04-17 08:53 UTC, ebbeknudsen approved these changes

2024-04-17 08:53 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/Models/Bundels/Bundle.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Models.Bundels;
Seems like there is a typo in the folder name: `Bundels` -> `Bundles`

2024-04-17 08:54 UTC, ebbeknudsen commented on source/OutgoingMessages.Domain/Queueing/OutgoingMessages/IOutgoingMessageRepository.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Queueing.OutgoingMessages
Looks good to me (maybe except the `Bundels` -> `Bundles` typo 😄)

2024-04-17 09:16 UTC, MadsDue reviewed
I am still not sure about the interfaces for the repositories. 

Should the domain layer be able to trigger execute I/O operations?
 
Currently it looks like the repositories is only used in the application layer, which I also would except.

2024-04-17 09:16 UTC, MadsDue commented on source/OutgoingMessages.Domain/Models/ReceiverMismatchException.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.Models;
Should we move this in to the Energinet.DataHub.EDI.OutgoingMessages.Domain.Models.ActorMessagesQueues namespace, that is the only place it is use

2024-04-17 09:16 UTC, MadsDue commented on source/OutgoingMessages.Domain/DocumentFactory.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain;
Consider moving this to Energinet.DataHub.EDI.OutgoingMessages.Domain.DocumentWriters

2024-04-17 09:16 UTC, MadsDue commented on source/OutgoingMessages.Domain/IMessageRecordParser.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain
Consider moving this to Energinet.DataHub.EDI.OutgoingMessages.Domain.DocumentWriters

2024-04-17 09:16 UTC, MadsDue commented on source/OutgoingMessages.Domain/MarketDocumentWriterMemoryStream.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain;
Consider moving this to Energinet.DataHub.EDI.OutgoingMessages.Domain.DocumentWriters

2024-04-17 09:16 UTC, MadsDue commented on source/OutgoingMessages.Domain/MessageRecordParser.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain
Consider moving this to Energinet.DataHub.EDI.OutgoingMessages.Domain.DocumentWriters

2024-04-17 10:25 UTC, lasrinnil commented on source/OutgoingMessages.Application/UseCases/DelegateMessage.cs
> -public class MessageDelegator
I could be! But I like that we have encapsulated it in its own "usecase" this way it's clear how we have implemented this particulier businesscase.

2024-04-18 07:54 UTC, RasmusGraabaek commented on source/OutgoingMessages.Application/UseCases/DelegateMessage.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Application.UseCases;
```suggestion
namespace Energinet.DataHub.EDI.OutgoingMessages.Application.Features;
```

2024-04-18 07:54 UTC, RasmusGraabaek commented on source/OutgoingMessages.Application/UseCases/DelegateMessage.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Application.UseCases;
Maybe?

2024-04-18 07:55 UTC, RasmusGraabaek commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataJsonDocumentWriter.cs
>  public class NotifyAggregatedMeasureDataJsonDocumentWriter : IDocumentWriter
```suggestion
public class NotifyAggregatedMeasureDataCIMJsonDocumentWriter : IDocumentWriter
```
?

2024-04-18 07:56 UTC, RasmusGraabaek commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataJsonDocumentWriter.cs
>  public class NotifyAggregatedMeasureDataJsonDocumentWriter : IDocumentWriter
This suggestion holds for all json stuff

2024-04-18 10:15 UTC, lasrinnil commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyAggregatedMeasureData/NotifyAggregatedMeasureDataJsonDocumentWriter.cs
>  public class NotifyAggregatedMeasureDataJsonDocumentWriter : IDocumentWriter
done

2024-04-18 10:15 UTC, lasrinnil commented on source/OutgoingMessages.Application/UseCases/DelegateMessage.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Application.UseCases;
No.

2024-04-18 10:19 UTC, lasrinnil commented on source/OutgoingMessages.Domain/DocumentWriters/NotifyWholesaleServices/WholesaleCalculationMarketActivityRecord.cs
> +namespace Energinet.DataHub.EDI.OutgoingMessages.Domain.DocumentWriters.NotifyWholesaleServices;
Its one of the serialized classes - so I would prefer not to :)

2024-04-18 11:25 UTC, RasmusGraabaek approved these changes

2024-04-18 11:29 UTC, merged