feat: create wholesale services messages from total montlhy amount result events
Energinet-DataHub/opengeh-edi pull request #989
Opened 2024-04-29 13:29 UTC by MadsDue

## Description

## References

2024-05-15 09:02 UTC, ebbeknudsen commented on source/IntegrationEvents.Infrastructure/Factories/WholesaleServicesMessageFactory.cs
>              message);
Was this supposed to be when creating `TotalMonthlyAmountPerCharge` or is this change just unrelated to the task?

2024-05-15 10:14 UTC, ebbeknudsen requested changes

2024-05-15 10:14 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
>              .Be(expectedSettlementMethod.Code);
Indentation

2024-05-15 10:14 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
> +                .WithMessage("The given key was not present in the dictionary.");
Use `.TryGetProperty()` instead, like `.MessageIdExists()` (multiple places)

2024-05-15 10:14 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/IAssertNotifyWholesaleServicesDocument.cs
> +    IAssertNotifyWholesaleServicesDocument HasSettlementMethod(SettlementMethod? expectedSettlementMethod);
I think all these should use our existing pattern of `.TransactionIdExists()` etc. instead. This makes it explicit when we allow the value to be empty when calling the asserter. Moving the logic into the asserter open the possiblity where we accidently call the `.HasSettlementMethod()` with a null value where we didn't intent to (there is a lot of cases where a null value isn't valid)

2024-05-15 10:14 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/IAssertNotifyWholesaleServicesDocument.cs
I think it would make sense to have a new test in `NotifyWholesaleServicesDocumentWriterTests` that tests these new allowed nullable values still writes a valid document. Something like a `Can_create_notifyWholesaleServices_document_with_optional_values_as_null`

2024-05-15 10:22 UTC, MadsDue commented on source/IntegrationEvents.Infrastructure/Factories/WholesaleServicesMessageFactory.cs
>              message);
Not related and not fixing anything :) just an attempt to make it more readable. But it will be rewritten in this PR https://github.com/Energinet-DataHub/opengeh-edi/pull/1015

2024-05-15 10:24 UTC, MadsDue commented on source/IntegrationEvents.Infrastructure/Factories/WholesaleServicesMessageFactory.cs
Not related and not fixing anything :) just an attempt to make it more readable. But it will be rewritten in this PR https://github.com/Energinet-DataHub/opengeh-edi/pull/1015

2024-05-15 10:26 UTC, MadsDue commented on source/IntegrationEvents.Infrastructure/Factories/WholesaleServicesTotalSumMessageFactory.cs
> +            BusinessReasonMapper.Map(totalMonthlyAmountResultProducedV1.CalculationType).Name,
Currently the outgoing message dto and outgoing message's serialized context are serializing the BusinessReason as a string.

2024-05-15 10:35 UTC, MadsDue commented on source/IntegrationTests/Behaviours/IntegrationEvents/GivenTotalMonthlyAmountResultProducedV1ProcessorTests.cs
> +    public async Task When_ChargeOwnerActorPeeksMessage_Then_ReceivesCorrectNotifyWholesaleServicesDocument(
Nope, only one message is created per event: https://miro.com/app/board/uXjVMCOTRs0=/?moveToWidget=3458764588941612399&cot=14 (Scenario E, F and G is for total sum)

2024-05-15 10:42 UTC, MadsDue commented on source/OutgoingMessages.Application/OutgoingMessagesClient.cs
> +    public async Task<OutgoingMessageId> EnqueueAndCommitAsync(
Since the WholesaleServicesMessageDto and WholesaleServicesTotalSumMessageDto is not having the same business logic (totalSum = 1 message) option 1 is out and since they both needs to become a RSM019 I like that we have one type WholesaleServicesMessageDto that represent RSM019, which others can inherit from. But let us have a chat about it

2024-05-15 10:43 UTC, MadsDue commented on source/OutgoingMessages.Domain/Models/OutgoingMessages/OutgoingMessage.cs
> +        public static OutgoingMessage CreateMessage(
See previous answer.

2024-05-15 10:43 UTC, MadsDue commented on source/OutgoingMessages.Interfaces/IOutgoingMessagesClient.cs
> +    Task<OutgoingMessageId> EnqueueAndCommitAsync(WholesaleServicesTotalSumMessageDto wholesaleServicesTotalSumMessage, CancellationToken cancellationToken);
See previous answer.

2024-05-16 08:37 UTC, ebbeknudsen approved these changes

2024-05-16 08:37 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
> +            .GetProperty("resolution");
We can use `.TryGetProperty()` instead of having to catch an exception

2024-05-16 08:37 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
> +            .WithMessage("The given key was not present in the dictionary.");
IMO `.TryGetProperty("quality". out _).Should().BeTrue()` is cleaner

2024-05-16 08:37 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/AssertNotifyWholesaleServicesJsonDocument.cs
> +    public IAssertNotifyWholesaleServicesDocument HasSinglePointWithAmount(DecimalValue expectedAmount)
Is there any difference between this function and just using the `.HasPoints()` with a single point?

2024-05-16 08:37 UTC, ebbeknudsen commented on source/Tests/Infrastructure/OutgoingMessages/NotifyWholesaleServices/NotifyWholesaleServicesDocumentWriterTests.cs
> +            InstantPattern.General.Parse(SampleData.Timestamp).Value);
Can't we use the `_wholesaleServicesSeriesBuilder` like in the `Can_create_notifyWholesaleServices_document` test?

2024-05-16 08:42 UTC, MadsDue commented on source/IntegrationTests/DocumentAsserters/NotifyWholesaleServicesDocumentAsserter.cs
> +            asserter.HasSinglePointWithAmount(assertionInput.Points.First().Amount);
var isTotalMonthlyAmount = assertionInput.Points.First().Price is null;
if (isTotalMonthlyAmount )

2024-05-16 09:28 UTC, merged